export class Employee{
  emp_ID:number
  emp_name:string
  // photo:ResourceStr
  gender:string
  dep_ID:number
  dep_name:string
  pos_ID:number
  pos_name:string
  date:string
  entermode:string
  birthday:string
  phone:string
  email:string
  address:string
  work_experience:string
  academic_background:string
  emp_type:string
  confirm_date:string
  intern_situation:string
  intern_detail:string
  confirm_process:string
  annual_holiday:number
  lieu_holiday:number
  password:string


  // constructor(emp_ID: number, emp_name: string, gender: string, dep_ID: number, pos_ID: number, date: string,
  // entermode:string,birthday:string,phone:string,email:string,address:string) {
  //   this.emp_ID=emp_ID
  //   this.emp_name=emp_name
  //   this.gender=gender
  //   this.dep_ID=dep_ID
  //   this.dep_name=''
  //   this.pos_ID=pos_ID
  //   this.pos_name=''
  //   this.date=date
  //   this.entermode=entermode
  //   this.birthday=birthday
  //   this.phone=phone
  //   this.email=email
  //   this.address=address
  //   this.work_experience=''
  //   this.academic_background=''
  //   this.emp_type='实习生'
  //   this.confirm_date=''
  //   this.intern_situation='正常实习'
  //   this.intern_detail=''
  //
  // }
}