
export class employee{
  emp_ID:number
  password:string
  emp_name:string
  // photo:ResourceStr
  gender:string
  dep_ID:number
  dep_name:string
  pos_ID:number
  pos_name:string
  date:string
  entermode:string
  birthday:string
  phone:string
  email:string
  address:string
  work_experience:string
  academic_background:string
  emp_type:string
  confirm_date:string
  intern_situation:string
  intern_detail:string
}